# SPDX-License-Identifier: GPL-2.0-only
# Ported from Linux drivers/pinctrl/intel/pinctrl-cherryview.c.
# Copyright (C) 2014-2020 Intel Corporation; Mika Westerberg, Ning Li, Alan Cox.

[package]
name = "pinctrl-cherryview-core"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-2.0-only"

[lib]
path = "src/lib.rs"

[workspace]
