// SPDX-License-Identifier: GPL-2.0-only
//! Pure construction and completion of SMBus transactions emulated by plain I2C messages.
//!
//! Ported from Linux `drivers/i2c/i2c-core-smbus.c:319-521`. Original copyright holders: Frodo
//! Looijaard, Mark Studebaker, Jean Delvare, and the Linux I2C authors.
//!
//! The caller owns I/O. [`emulate`] returns one or two complete message descriptions; after the
//! caller fills read buffers, [`decode_read`] turns the response into an SMBus value.

use crate::pec;
use crate::protocol::{Direction, Transaction, I2C_SMBUS_BLOCK_MAX};
use i2c_core_msg_core::flags::{is_read, I2C_M_RD, I2C_M_RECV_LEN};

/// Buffer size Linux reserves for the first emulated message: block maximum plus command, length,
/// and possible PEC (`i2c-core-smbus.c:334`).
pub const WRITE_BUFFER_CAPACITY: usize = I2C_SMBUS_BLOCK_MAX + 3; // i2c-core-smbus.c:334
/// Buffer size Linux reserves for a read: block maximum plus length and possible PEC
/// (`i2c-core-smbus.c:335`).
pub const READ_BUFFER_CAPACITY: usize = I2C_SMBUS_BLOCK_MAX + 2; // i2c-core-smbus.c:335

/// SMBus argument or result storage corresponding to Linux `union i2c_smbus_data`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Data {
    /// No payload is required (QUICK and BYTE read).
    None,
    /// One-byte payload.
    Byte(u8),
    /// Little-endian two-byte payload.
    Word(u16),
    /// Block payload; `length` bytes are valid in `bytes`.
    Block {
        /// Valid payload byte count.
        length: u8,
        /// Payload bytes, excluding the SMBus wire length byte.
        bytes: [u8; I2C_SMBUS_BLOCK_MAX],
    },
}

/// One plain-I2C message generated by SMBus emulation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Message {
    /// Seven-bit SMBus address. Address validation/encoding belongs to i2c-core-msg-core.
    pub address: u8,
    /// Existing caller flags plus flags required by SMBus emulation. The definitions come from
    /// i2c-core-msg-core rather than being duplicated here.
    pub flags: u16,
    /// Transfer length before hardware processes a receive-length byte.
    pub length: usize,
    /// Message storage. Only `length` bytes are initially meaningful.
    pub buffer: [u8; WRITE_BUFFER_CAPACITY],
}

const EMPTY_MESSAGE: Message = Message {
    address: 0,
    flags: 0,
    length: 0,
    buffer: [0; WRITE_BUFFER_CAPACITY],
};

/// Complete emulation plan containing one or two plain-I2C messages.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Transfer {
    /// Messages in wire order.
    pub messages: [Message; 2],
    /// Number of live entries in `messages`.
    pub message_count: usize,
    /// Effective completion direction. Procedure calls always become reads.
    pub completion_direction: Direction,
    /// Partial PEC from the write phase of a write-then-read transfer.
    pub partial_pec: u8,
    /// Whether PEC was enabled after transaction exclusions.
    pub pec: bool,
}

/// Why emulation refused a request or device response.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Refusal {
    /// SMBus block write exceeded the protocol maximum.
    InvalidBlockWriteSize {
        /// Refused payload length.
        length: usize,
        /// Inclusive SMBus bound.
        maximum: usize,
    },
    /// I2C-block read or write exceeded the protocol maximum.
    InvalidI2cBlockSize {
        /// Whether the refused operation was a read.
        direction: Direction,
        /// Refused payload length.
        length: usize,
        /// Inclusive SMBus bound.
        maximum: usize,
    },
    /// The supplied data variant does not match the transaction's required payload.
    WrongDataForTransaction {
        /// Transaction that refused the value.
        transaction: Transaction,
        /// Named required data shape.
        expected: &'static str,
    },
    /// The device's FIRST BLOCK_DATA response byte exceeded 32.
    InvalidBlockSizeReturned {
        /// Hostile or broken device-supplied length byte.
        length: u8,
        /// Inclusive SMBus bound.
        maximum: usize,
    },
    /// Fewer response bytes were made available than the protocol says are required.
    ResponseTooShort {
        /// Bytes made available by the caller/bus layer.
        length: usize,
        /// Required byte count.
        minimum: usize,
    },
    /// Packet error checking refused the response or append operation.
    Pec(pec::PecRefusal),
}

impl From<pec::PecRefusal> for Refusal {
    fn from(value: pec::PecRefusal) -> Self {
        Self::Pec(value)
    }
}

/// Build Linux's plain-I2C message sequence for one SMBus transaction.
///
/// `message_flags` are existing I2C message flags selected by the caller; Linux copies them to both
/// messages and ORs in `I2C_M_RD`/`I2C_M_RECV_LEN` (`i2c-core-smbus.c:339-350,357-451`).
/// This ports the complete switch at `i2c-core-smbus.c:356-455`, including the special direction
/// rules for QUICK, receive BYTE, PROC_CALL, and BLOCK_PROC_CALL and PEC placement at :457-468.
pub fn emulate(
    address: u8,
    message_flags: u16,
    direction: Direction,
    command: u8,
    transaction: Transaction,
    data: Data,
    client_pec: bool,
) -> Result<Transfer, Refusal> {
    let mut messages = [EMPTY_MESSAGE; 2];
    messages[0].address = address;
    messages[0].flags = message_flags;
    messages[0].length = 1;
    messages[0].buffer[0] = command;
    messages[1].address = address;
    messages[1].flags = message_flags | I2C_M_RD;

    let mut count = if direction == Direction::Read { 2 } else { 1 };
    let mut completion_direction = direction;

    match transaction {
        Transaction::Quick => {
            messages[0].length = 0;
            if direction == Direction::Read {
                messages[0].flags |= I2C_M_RD;
            }
            count = 1;
        }
        Transaction::Byte => {
            if direction == Direction::Read {
                messages[0].flags |= I2C_M_RD;
                count = 1;
            }
        }
        Transaction::ByteData => {
            if direction == Direction::Read {
                messages[1].length = 1;
            } else {
                messages[0].length = 2;
                messages[0].buffer[1] = require_byte(transaction, data)?;
            }
        }
        Transaction::WordData => {
            if direction == Direction::Read {
                messages[1].length = 2;
            } else {
                messages[0].length = 3;
                put_word(&mut messages[0].buffer, require_word(transaction, data)?);
            }
        }
        Transaction::ProcCall => {
            count = 2;
            completion_direction = Direction::Read;
            messages[0].length = 3;
            messages[1].length = 2;
            put_word(&mut messages[0].buffer, require_word(transaction, data)?);
        }
        Transaction::BlockData => {
            if direction == Direction::Read {
                messages[1].flags |= I2C_M_RECV_LEN;
                messages[1].length = 1;
            } else {
                let (length, bytes) = require_block(transaction, data)?;
                validate_block_write(length as usize)?;
                messages[0].length = length as usize + 2;
                messages[0].buffer[1] = length;
                messages[0].buffer[2..messages[0].length]
                    .copy_from_slice(&bytes[..length as usize]);
            }
        }
        Transaction::BlockProcCall => {
            count = 2;
            completion_direction = Direction::Read;
            let (length, bytes) = require_block(transaction, data)?;
            validate_block_write(length as usize)?;
            messages[0].length = length as usize + 2;
            messages[0].buffer[1] = length;
            messages[0].buffer[2..messages[0].length].copy_from_slice(&bytes[..length as usize]);
            messages[1].flags |= I2C_M_RECV_LEN;
            messages[1].length = 1;
        }
        Transaction::I2cBlockData => {
            let (length, bytes) = require_block(transaction, data)?;
            if length as usize > I2C_SMBUS_BLOCK_MAX {
                return Err(Refusal::InvalidI2cBlockSize {
                    direction,
                    length: length as usize,
                    maximum: I2C_SMBUS_BLOCK_MAX,
                });
            }
            if direction == Direction::Read {
                messages[1].length = length as usize;
            } else {
                messages[0].length = length as usize + 1;
                messages[0].buffer[1..messages[0].length]
                    .copy_from_slice(&bytes[..length as usize]);
            }
        }
    }

    let use_pec = pec::wants_pec(client_pec, transaction);
    let mut partial_pec = 0;
    if use_pec {
        if !is_read(messages[0].flags) {
            if count == 1 {
                let length = messages[0].length;
                messages[0].length =
                    pec::append_write_pec(address, &mut messages[0].buffer, length)?;
            } else {
                partial_pec =
                    pec::message_pec(0, address, false, &messages[0].buffer[..messages[0].length]);
            }
        }
        if is_read(messages[count - 1].flags) {
            messages[count - 1].length += 1;
        }
    }

    Ok(Transfer {
        messages,
        message_count: count,
        completion_direction,
        partial_pec,
        pec: use_pec,
    })
}

/// Decode a completed read from an emulated transfer.
///
/// The caller supplies the actual read length because receive-length bus drivers extend the
/// initially-one-byte message. For BLOCK_DATA and BLOCK_PROC_CALL, byte zero is checked before any
/// copy (`i2c-core-smbus.c:501-510`); 33 succeeds and means length byte plus 32 payload bytes, while
/// a first byte of 33 or 255 returns [`Refusal::InvalidBlockSizeReturned`] rather than clamping.
pub fn decode_read(
    transaction: Transaction,
    transfer: &Transfer,
    actual_read_length: usize,
) -> Result<Data, Refusal> {
    if transfer.completion_direction != Direction::Read {
        return Ok(Data::None);
    }
    let index = transfer.message_count - 1;
    let message = &transfer.messages[index];
    if actual_read_length > message.buffer.len() {
        return Err(Refusal::ResponseTooShort {
            length: message.buffer.len(),
            minimum: actual_read_length,
        });
    }

    let payload_length = if transfer.pec && is_read(message.flags) {
        pec::check_read_pec(
            transfer.partial_pec,
            message.address,
            &message.buffer,
            actual_read_length,
        )?
    } else {
        actual_read_length
    };

    match transaction {
        Transaction::Quick => Ok(Data::None),
        Transaction::Byte => {
            require_response(payload_length, 1)?;
            Ok(Data::Byte(message.buffer[0]))
        }
        Transaction::ByteData => {
            require_response(payload_length, 1)?;
            Ok(Data::Byte(message.buffer[0]))
        }
        Transaction::WordData | Transaction::ProcCall => {
            require_response(payload_length, 2)?;
            Ok(Data::Word(
                message.buffer[0] as u16 | ((message.buffer[1] as u16) << 8),
            ))
        }
        Transaction::I2cBlockData => {
            require_response(payload_length, message.length)?;
            let length = message.length;
            let mut bytes = [0; I2C_SMBUS_BLOCK_MAX];
            bytes[..length].copy_from_slice(&message.buffer[..length]);
            Ok(Data::Block {
                length: length as u8,
                bytes,
            })
        }
        Transaction::BlockData | Transaction::BlockProcCall => {
            require_response(payload_length, 1)?;
            let length = message.buffer[0];
            if length as usize > I2C_SMBUS_BLOCK_MAX {
                return Err(Refusal::InvalidBlockSizeReturned {
                    length,
                    maximum: I2C_SMBUS_BLOCK_MAX,
                });
            }
            require_response(payload_length, length as usize + 1)?;
            let mut bytes = [0; I2C_SMBUS_BLOCK_MAX];
            bytes[..length as usize].copy_from_slice(&message.buffer[1..length as usize + 1]);
            Ok(Data::Block { length, bytes })
        }
    }
}

fn require_byte(transaction: Transaction, data: Data) -> Result<u8, Refusal> {
    match data {
        Data::Byte(value) => Ok(value),
        _ => Err(Refusal::WrongDataForTransaction {
            transaction,
            expected: "byte",
        }),
    }
}

fn require_word(transaction: Transaction, data: Data) -> Result<u16, Refusal> {
    match data {
        Data::Word(value) => Ok(value),
        _ => Err(Refusal::WrongDataForTransaction {
            transaction,
            expected: "word",
        }),
    }
}

fn require_block(
    transaction: Transaction,
    data: Data,
) -> Result<(u8, [u8; I2C_SMBUS_BLOCK_MAX]), Refusal> {
    match data {
        Data::Block { length, bytes } => Ok((length, bytes)),
        _ => Err(Refusal::WrongDataForTransaction {
            transaction,
            expected: "block",
        }),
    }
}

fn validate_block_write(length: usize) -> Result<(), Refusal> {
    if length > I2C_SMBUS_BLOCK_MAX {
        Err(Refusal::InvalidBlockWriteSize {
            length,
            maximum: I2C_SMBUS_BLOCK_MAX,
        })
    } else {
        Ok(())
    }
}

fn put_word(buffer: &mut [u8], word: u16) {
    buffer[1] = word as u8;
    buffer[2] = (word >> 8) as u8;
}

fn require_response(length: usize, minimum: usize) -> Result<(), Refusal> {
    if length < minimum {
        Err(Refusal::ResponseTooShort { length, minimum })
    } else {
        Ok(())
    }
}
