# SPDX-License-Identifier: GPL-2.0-only
# Ported from Linux drivers/usb/host/xhci-mem.c, xhci.h, xhci-caps.h, and xhci.c.
# Copyright (C) 2008 Intel Corp.; original author Sarah Sharp.

[package]
name = "xhci-mem-core"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-2.0-only"

[lib]
path = "src/lib.rs"

[workspace]
