# SPDX-License-Identifier: GPL-2.0-only
# Pure register encodings ported from Linux drivers/gpio/gpio-crystalcove.c.
# Copyright (C) 2012, 2014 Intel Corporation. All rights reserved.

[package]
name = "gpio-crystalcove-core"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-2.0-only"

[lib]
path = "src/lib.rs"

[workspace]
